name: flutter_local_auth_invisible
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader and Touch ID with no visible dialog on Android.
homepage: https://github.com/priezz/flutter_local_auth_invisible
version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  intl: ^0.17.0
  meta: ^1.3.0
  platform: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
